# Generated by Django 4.2.30 on 2026-06-19 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0002_transaction_easebuzz'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transaction',
            table='payment_payu',
        ),
    ]
