# Generated by Django 4.2.30 on 2026-06-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0003_alter_transaction_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='productinfo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction_easebuzz',
            name='productinfo',
            field=models.TextField(blank=True, null=True, verbose_name='Product Information'),
        ),
    ]
