# Generated by Django 4.2.30 on 2026-06-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0004_alter_transaction_productinfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='productinfo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='transaction_easebuzz',
            name='productinfo',
            field=models.TextField(verbose_name='Product Information'),
        ),
    ]
