# Generated by Django 4.2.30 on 2026-06-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0005_alter_transaction_productinfo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='firstname',
            new_name='customer_name',
        ),
        migrations.AddField(
            model_name='transaction',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='loan_ac_no',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
