# Generated by Django 4.2.30 on 2026-06-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0007_rename_firstname_transaction_easebuzz_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction_easebuzz',
            name='phone',
            field=models.CharField(max_length=10, verbose_name='Phone Number'),
        ),
    ]
