# Generated by Django 4.2.30 on 2026-06-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0008_alter_transaction_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finance_id', models.IntegerField(default=0)),
                ('chart_of_account_id', models.IntegerField(default=0)),
                ('agreement_number', models.CharField(max_length=100)),
                ('ledger_code', models.CharField(blank=True, max_length=100, null=True)),
                ('received_date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('lpc', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('lpc_date', models.DateTimeField(blank=True, null=True)),
                ('cheque_no', models.CharField(blank=True, max_length=50, null=True)),
                ('collection_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('voucher_no', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('loan_receipt_mode', models.CharField(default='Select', max_length=50)),
                ('bank_channel_type', models.CharField(default='Select', max_length=50)),
                ('policy_payment_type_id', models.CharField(default='EMIPayment', max_length=50)),
                ('journal_ids', models.JSONField(blank=True, default=list)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('is_settlement', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_code', models.IntegerField(default=0)),
                ('is_accept_emi_with_receive_advance', models.BooleanField(default=True)),
                ('api_status', models.CharField(default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payment_logs',
            },
        ),
    ]
