# Generated by Django 4.2.30 on 2026-06-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0009_getpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='getpayment',
            name='balance_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='getpayment',
            name='bank_ref_num',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='getpayment',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='getpayment',
            name='emi_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='getpayment',
            name='payment_gateway',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='getpayment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='getpayment',
            name='api_status',
            field=models.CharField(default='INITIATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='getpayment',
            name='bank_channel_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='getpayment',
            name='loan_receipt_mode',
            field=models.CharField(default='Online', max_length=50),
        ),
        migrations.AlterField(
            model_name='getpayment',
            name='received_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
