# Generated by Django 4.2.30 on 2026-06-26 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0010_getpayment_balance_amount_getpayment_bank_ref_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getpayment',
            name='api_status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
