# Generated by Django 4.2.30 on 2026-06-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0011_alter_getpayment_api_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='getpayment',
            name='bank_channel_type',
        ),
        migrations.RemoveField(
            model_name='getpayment',
            name='chart_of_account_id',
        ),
        migrations.RemoveField(
            model_name='getpayment',
            name='cheque_no',
        ),
        migrations.RemoveField(
            model_name='getpayment',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='getpayment',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='getpayment',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='getpayment',
            name='is_accept_emi_with_receive_advance',
        ),
        migrations.RemoveField(
            model_name='getpayment',
            name='is_settlement',
        ),
        migrations.RemoveField(
            model_name='getpayment',
            name='journal_ids',
        ),
        migrations.RemoveField(
            model_name='getpayment',
            name='ledger_code',
        ),
        migrations.RemoveField(
            model_name='getpayment',
            name='loan_receipt_mode',
        ),
        migrations.RemoveField(
            model_name='getpayment',
            name='lpc_date',
        ),
        migrations.RemoveField(
            model_name='getpayment',
            name='policy_payment_type_id',
        ),
        migrations.RemoveField(
            model_name='getpayment',
            name='voucher_no',
        ),
        migrations.AddField(
            model_name='getpayment',
            name='log_type',
            field=models.CharField(default='FETCH_LEAD', help_text='TOKEN_GEN, FETCH_LEAD, or PAYMENT_POST', max_length=50),
        ),
    ]
