# Generated by Django 4.2.30 on 2026-06-26 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0012_remove_getpayment_bank_channel_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='getpayment',
            name='log_type',
        ),
    ]
