# Generated by Django 4.2.30 on 2026-06-26 10:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0013_remove_getpayment_log_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='getpayment',
            name='agreement_number',
        ),
        migrations.RemoveField(
            model_name='getpayment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='getpayment',
            name='api_status',
        ),
        migrations.RemoveField(
            model_name='getpayment',
            name='balance_amount',
        ),
        migrations.RemoveField(
            model_name='getpayment',
            name='bank_ref_num',
        ),
        migrations.RemoveField(
            model_name='getpayment',
            name='collection_charges',
        ),
        migrations.RemoveField(
            model_name='getpayment',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='getpayment',
            name='emi_amount',
        ),
        migrations.RemoveField(
            model_name='getpayment',
            name='error_code',
        ),
        migrations.RemoveField(
            model_name='getpayment',
            name='finance_id',
        ),
        migrations.RemoveField(
            model_name='getpayment',
            name='lpc',
        ),
        migrations.RemoveField(
            model_name='getpayment',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='getpayment',
            name='payment_gateway',
        ),
        migrations.RemoveField(
            model_name='getpayment',
            name='received_date',
        ),
        migrations.RemoveField(
            model_name='getpayment',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='getpayment',
            name='request_payload',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='getpayment',
            name='response_payload',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='getpayment',
            name='status_code',
            field=models.IntegerField(blank=True, help_text='HTTP Status Code (e.g., 200, 400, 504)', null=True),
        ),
        migrations.AddField(
            model_name='getpayment',
            name='type',
            field=models.CharField(default=django.utils.timezone.now, help_text='Auth Token, GetLoanDetails, or PostLoanDetails', max_length=50),
            preserve_default=False,
        ),
    ]
