# Generated by Django 4.2.30 on 2026-06-26 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0014_remove_getpayment_agreement_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payu_transactions', to='Payment.getpayment'),
        ),
        migrations.AddField(
            model_name='transaction_easebuzz',
            name='payment_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='easebuzz_transactions', to='Payment.getpayment'),
        ),
    ]
