# Generated by Django 4.2.30 on 2026-06-27 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0015_transaction_payment_log_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='getpayment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
