# Generated by Django 4.2.30 on 2026-06-27 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0016_getpayment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='getpayment',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Links child logs (Get/Post) to their parent log (Auth Token)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_logs', to='Payment.getpayment'),
        ),
        migrations.AlterField(
            model_name='getpayment',
            name='status',
            field=models.CharField(default='PENDING', help_text='PENDING, SUCCESS, FAILED', max_length=20),
        ),
    ]
