# Generated by Django 4.2.30 on 2026-06-27 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0017_getpayment_parent_alter_getpayment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='getpayment',
            name='status',
        ),
    ]
